tasktracking/tasks/urls.py
from django.urls import path
from django.urls import path, include # new
from tasks import views
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView


from .views import SignUpView

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastrar_tarefa', views.cadastrar_tarefa, name='cadastrar_tarefa'),
    path('detalhar_tarefa/<int:pk>/', views.TarefaDetailView.as_view(), name='detalhar_tarefa'),
    path('cadastrar_link', views.cadastrar_link, name='cadastrar_link'),
    path('cadastrar_tag', views.cadastrar_tag, name='cadastrar_tag'),
    path('pesquisar_tarefas', views.buscar_tarefas, name='buscar_tarefas'),
    path('cadastrar_execucao', views.cadastrar_execucao, name='cadastrar_execucao'),
    path('accounts/', include('django.contrib.auth.urls')), # new
    #path('accounts/', include('accounts.urls')), # new
    path('signup/', SignUpView.as_view(), name='signup'),
    #path('', TemplateView.as_view(template_name='home.html'), name='home'), # new
]

tasktracking/tasktracking/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic.base import TemplateView # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('accounts/', include('django.contrib.auth.urls')), # new
    path('', TemplateView.as_view(template_name='home.html'), name='home'), # new
]

tasktracking/tasks/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

class Usuario(models.Model):
    """
        Gabriel Gonçalo
    Args:
        models ([type]): [description]
    """
    nome = models.CharField(max_length=200)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        return self.nome


class Tag(models.Model):
    """
        Jonas
    Args:
        models ([type]): [description]
    """
    tarefa = models.ForeignKey('Tarefa', on_delete=models.CASCADE, null=True)
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome


class Link(models.Model):
    """
        Wanessa
    Args:
        models ([type]): [description]
    """
    tarefa = models.ForeignKey('Tarefa', on_delete=models.CASCADE, null=True)
    nome = models.CharField(max_length=50)
    url = models.URLField()

    def __str__(self):
        return self.nome + ' ' + self.url


class Tarefa(models.Model):
    """
        Arthur
    Args:
        models ([type]): [description]
    """
    STATUS_CHOICES = (
        ("1", "Planejada"),
        ("2", "Em Execução"),
        ("3", "Concluída"),
        ("4", "Cancelada"),
    )
    SITUACAO_CHOICES = (
        ("1", "Aberta"),
        ("2", "Abandonada"),
        ("3", "Fechada"),
    )

    identificador = models.CharField(max_length=50)
    nome = models.CharField(max_length=100)
    descrição = models.CharField(max_length=250)
    criada_em = models.DateTimeField(auto_now_add=True)
    fechada_em = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    situacao = models.CharField(max_length=1, choices=SITUACAO_CHOICES)
    usuario = models.ForeignKey(Usuario, on_delete=models.PROTECT)

    def __str__(self):
        return self.identificador + ' - ' + self.nome


class Execucao(models.Model):
    """[summary]
        Pedro
    Args:
        models ([type]): [Representa uma execução de uma tarefa.]
    """
    PARADA = "1"
    EXECUTANDO = "2"
    PAUSADA = "3"

    STATUS_CHOICES = (
        ("1", "Parada"),
        ("2", "Executando"),
        ("3", "Pausada"),
    )

    inicio = models.DateTimeField()
    fim = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, null=True)
    tarefa = models.ForeignKey(Tarefa, on_delete=models.PROTECT)
    usuario = models.ForeignKey(Usuario, on_delete=models.PROTECT)

tasktracking/tasks/forms.py
from django import forms
from tasks.models import Link, Tarefa, Tag


class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = '__all__'

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = '__all__'

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

tasktracking/tasks/views.py
from django.http import request
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic import DetailView
from datetime import datetime
from tasks.forms import LinkForm, TarefaForm, TagForm
from django.core.paginator import Paginator
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

from tasks.models import Execucao, Tarefa
from tasks.models import Link
from tasks.models import Tag

def index(request):
    """View function for home page of site."""

    lista_tarefas  = Tarefa.objects.all().order_by('-criada_em')

    paginator = Paginator(lista_tarefas, 3)

    page_number = request.GET.get('page')
    if page_number is None:
        page_number = 1

    lista_tarefas_paginada = paginator.get_page(page_number)

    context = {
        'lista_tarefas_paginada': lista_tarefas_paginada
    }

    return render(request, 'tasks/index.html', context=context)


def cadastrar_tarefa(request):
    if request.method == 'POST':
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            form_tarefa.save()
            return redirect('index')
    else:
        form_tarefa = TarefaForm()

    context = {
        'form_tarefa': form_tarefa
    }
    return render(request, 'tasks/tarefa/cadastrar_tarefa.html', context=context)


class TarefaDetailView(DetailView):
    model = Tarefa
    template_name = 'tasks/tarefa/detalhar.html'


def cadastrar_link(request):
    if request.method == 'POST':
        form_link = LinkForm(request.POST)
        if form_link.is_valid():
            form_link.save()
            return redirect('index')
    else:
        form_link = LinkForm()

    context = {
        'form_link': form_link
    }
    return render(request, 'tasks/link/cadastrar_link.html', context=context)


def cadastrar_tag(request):
    if request.method == 'POST':
        form_tag = TagForm(request.POST)
        if form_tag.is_valid():
            form_tag.save()
            return redirect('index')
    else:
        form_tag = TagForm()

    context = {
        'form_tag': form_tag
    }
    return render(request, 'tasks/tags/cadastrar_tag.html', context=context)


def buscar_tarefas(request):

    search = request.POST.get("search")

    lista_tarefas = Tarefa.objects.filter(nome__icontains=search)

    context = {
       'lista_tarefas': lista_tarefas
    }
    return render(request, 'tasks/index.html', context=context)


def cadastrar_execucao(request):
    tarefa_pk = request.GET.get('tarefa_pk')
    print('Passando na View!' + tarefa_pk)

    tarefa = Tarefa.objects.get(pk=tarefa_pk)
    inicio = datetime.now()
    Execucao.objects.create(
        inicio=inicio, tarefa=tarefa, 
        status=Execucao.EXECUTANDO,
        usuario=tarefa.usuario)
    
    data = dict()
    return JsonResponse(data)


def stop_execucao(request):
    # Buscar uma execução da tarefa selecionda que esteja EXECUTANDO
    # Colocar o status PARADA e a data de fim.
    data = dict()
    return JsonResponse(data)

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

tasktracking/tasks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt_br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block titulo %}<title>PWeb 2020.6</title>{% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/link.css' %}">
</head>

<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <li class="navbar-brand" href="#">Tasks Tracking</li>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul type="disc" class="navbar-nav">
                    <li><a class="nav-link" href="/">Tarefas</a></li>
                    <li><a class="nav-link" href="/cadastrar_tag">Tags</a></li>
                    <li><a class="nav-link" href="/cadastrar_link">Links</a></li>
                    <li><a class="nav-link" href="#">Execuções</a></li>
                    <li><a class="nav-link" href="">
                    {% if user.is_authenticated %}
                        Oi {{ user.username }}!
                        <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock %}

        <footer id="rodape">
            <p>Copyright &copy; 2020 - by Turma de Pweb 2020.6</br></p>
        </footer>
    </div>

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    {% block myscripts %}{% endblock myscripts %}
</body>
</html>

tasktracking/tasks/templates/tasks/index.html
{% extends "base.html" %}
{% load static %}

{% block titulo %}
  <title>PWeb 2020.6 - Index</title>
{% endblock %}

{% block content %}
<div class="offset-1 col-10 list-div">
  <div class="col-2 add-div">
    <a href="{% url 'cadastrar_tarefa' %}" class="btn">
      <i class="fas fa-plus"></i>
      <span class="add-tarefa">Adicionar Tarefa</span>
    </a>
  </div>

    <form action="/pesquisar_tarefas" method="post" class="col-9 search-div">
      {% csrf_token %}
      <input class="form-control" type="text" id="search" name="search"
      placeholder="Digite o nome da tarefa para buscar...">
      <button type="submit" class="fas fa-search btn-light">
      </button>
    </form>

  <ul class="task-list">
    {% for tarefa in lista_tarefas_paginada %}
      <li class="task-item">
        <span><i class="fas fa-play" onclick="start('{{ tarefa.pk }}')"></i></span>
        <span><i class="fas fa-pause" onclick="pause()"></i></span>
        <span><i class="fas fa-stop" onclick="stop()"></i></span>
        <span>&nbsp;</span>
        <a href="{% url 'detalhar_tarefa' tarefa.pk %}"
        <span>{{ tarefa }}</span>
        </a>

        <div id="counter" class="d-inline">00:00:00</div>

        <div class="tag_text">
          {% for tag in tarefa.tag_set.all %}
            {{ tag }}<span>&nbsp;</span>
          {% endfor %}
        </div>
        <input />
        <span><i class="fas fa-trash"></i></span>
        <span><i class="fas fa-edit"></i></span>
      </li>
    {% endfor %}
  </ul>

  <div class="pagination">
    <span class="step-links">
      {% if lista_tarefas_paginada.has_previous %}
        <a href="?page=1"><i class="fas fa-angle-double-left"></i></a>
        <a href="?page={{ lista_tarefas_paginada.previous_page_number }}">
          <i class="fas fa-angle-left"></i></a>
      {% else %}
        <a href="#" class="disabled button big previous">#</a>
      {% endif %}

      <span class="current">
        {{ lista_tarefas_paginada.number }} de {{ lista_tarefas_paginada.paginator.num_pages }}
      </span>

      {% if lista_tarefas_paginada.has_next %}
        <a href="?page={{ lista_tarefas_paginada.next_page_number }}"><i class="fas fa-angle-right"></i></i></a>
        <a href="?page={{ lista_tarefas_paginada.paginator.num_pages }}"><i class="fas fa-angle-double-right"></i></a>
        {%else%}
        <a href="#" class="button big next">#</a>
      {% endif %}
    </span>
  </div>

</div>
{% endblock%}

{% block myscripts %}
  <script src="{% static 'js/crom.js' %}"></script>
{% endblock myscripts %}

tasktracking/tasks/templates/tasks/link/cadastrar_link.html
{% extends "base.html" %}

{% block titulo %}
  <title>PWeb 2020.6 - Adicionar Link</title>
{% endblock %}

{% block content %}
<div class="container">
<form method="post">
    {% csrf_token %}

    <table class="table table-sm table-responsive-sm">
        {% for field in form_link.visible_fields %}
          <tr>
            <th class="align-middle">
              <label>{{ field.label_tag }}</label>
            </th>
            <td class="align-middle">{{ field }}
              {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
              {% endif %}
              {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
    </table>

    <div>
        <input type="submit" value="Salvar">
    </div>
</form>
</div>
{% endblock %}

tasktracking/tasks/templates/tasks/link/editar_link.html
<!DOCTYPE html>
<html lang="pt_br">
<head>
  {% block titulo %}<title>PWeb 2020.6</title>{% endblock %}
</head>
<body>
  {% block sidebar %}
    <!-- insert default navigation text for every page -->
  {% endblock %}
  {% block content %}
    <!-- default content text (typically empty) -->
  {% endblock %}
</body>
</html>

tasktracking/tasks/templates/tasks/link/excluir_link.html
<!DOCTYPE html>
<html lang="pt_br">
<head>
  {% block titulo %}<title>PWeb 2020.6</title>{% endblock %}
</head>
<body>
  {% block sidebar %}
    <!-- insert default navigation text for every page -->
  {% endblock %}
  {% block content %}
    <!-- default content text (typically empty) -->
  {% endblock %}
</body>
</html>

tasktracking/tasks/templates/tasks/link/listar_links.html
<!DOCTYPE html>
<html lang="pt_br">
<head>
  {% block titulo %}<title>PWeb 2020.6</title>{% endblock %}
</head>
<body>
  {% block sidebar %}
    <!-- insert default navigation text for every page -->
  {% endblock %}
  {% block content %}
    <!-- default content text (typically empty) -->
  {% endblock %}
</body>
</html>

tasktracking/tasks/templates/tasks/link/pesquisar_links.html
<!DOCTYPE html>
<html lang="pt_br">
<head>
  {% block titulo %}<title>PWeb 2020.6</title>{% endblock %}
</head>
<body>
  {% block sidebar %}
    <!-- insert default navigation text for every page -->
  {% endblock %}
  {% block content %}
    <!-- default content text (typically empty) -->
  {% endblock %}
</body>
</html>

tasktracking/tasks/templates/tasks/tags/cadastrar_tag.html
{% extends "base.html" %}

{% block titulo %}
  <title>PWeb 2020.6 - Adicionar Tags</title>
{% endblock %}

{% block content %}
<div class="container">
<form method="post">
    {% csrf_token %}

    <table class="table table-sm table-responsive-sm">
        {% for field in form_tag.visible_fields %}
          <tr>
            <th class="align-middle">
              <label>{{ field.label_tag }}</label>
            </th>
            <td class="align-middle">{{ field }}
              {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
              {% endif %}
              {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
    </table>

    <div>
        <input type="submit" value="Salvar">
    </div>
</form>
</div>
{% endblock %}

tasktracking/tasks/templates/tasks/tarefa/cadastrar_tarefa.html
{% extends "base.html" %}

{% block titulo %}
  <title>PWeb 2020.6 - Adicionar Tarefa</title>
{% endblock %}

{% block content %}
<div class="container">
<form method="post">
    {% csrf_token %}

    <table class="table table-sm table-responsive-sm">
        {% for field in form_tarefa.visible_fields %}
          <tr>
            <th class="align-middle">
              <label>{{ field.label_tag }}</label>
            </th>
            <td class="align-middle">{{ field }}
              {% if field.help_text %}
                <small style="color: grey">{{ field.help_text }}</small>
              {% endif %}
              {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
    </table>

    <div>
        <input type="submit" value="Salvar">
    </div>
</form>
</div>
{% endblock %}

tasktracking/tasks/templates/tasks/tarefa/detalhar.html
{% extends "base.html" %}

{% block titulo %}
<title>PWeb 2020.6 - Detalhar Tarefa</title>
{% endblock %}

{% block content %}
<div class="content">
    <table class="table table-striped table-sm table-bordered">
        <tr>
            <td class="font-weight-bold" width="20%">Identificador</td>
            <td>{{ object.identificador }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold" width="20%">Nome</td>
            <td>{{ object.nome }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold" width="20%">Descrição</td>
            <td>{{ object.descrição }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold" width="20%">Criação</td>
            <td>{{ object.criada_em }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold" width="20%">Fechamento</td>
            <td>{{ object.fechada_em }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold" width="20%">Status</td>
            <td>{{ object.status }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold" width="20%">Situação</td>
            <td>{{ object.situacao }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold" width="20%">Criador</td>
            <td>{{ object.usuario }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold" width="20%">Links</td>
            <td>
                <ul>
                {% for link in object.link_set.all %}
                    <li class="link">{{ link.nome }}:
                        <a href="{{ link.url }}">{{ link.url }}</a>
                    </li>
                {% endfor %}
                </ul>
            </td>
        </tr>
        <tr>
            <td class="font-weight-bold" width="20%">Tags</td>
            <td>
                {% for tag in object.tag_set.all %}
                    {{ tag }}<span>&nbsp;&nbsp;</span>
                {% endfor %}
            </td>
        </tr>
    </table>
</div>
{% endblock%}